### PR TITLE
Uniformize image/sound loading + use gif/wav from $XDG_DATA_HOME/bambam/data

### PR DESCRIPTION
**Pull request by mgodlewski**

### CODE REVIEW

**Comment by vn971** [comment]
It may be reasonable to move "chimp.bmp" to "chimp.png" first, and consider the rest of the PR separately. (I can PR, of course.)

**Comment by mgodlewski** [comment]
What's missing in order to merge ?

**Comment by vn971** [comment]
@mgodlewski If you're talking about merge conflicts:
I saw your PR and extracted the "chimp.bmp" conversion (making it more correct on colors, too). https://github.com/porridge/bambam/pull/7

**Comment by porridge** [comment]
Oh wow, @mgodlewski  I never saw your commits from May 22nd until now!
It looks good, but could you please rebase?

**Comment by porridge** [comment]
Actually, more important than rebasing, it would be great if you could squash the last two commits.

**Comment by porridge** [comment]
I mean the last two commits by @mgodlewski

**Comment by mgodlewski** [comment]
Hi,

I'm not able to squash my commits since they're already pushed.
To make it right, I can cancel this pull request and create 2 separated ones : 
- one to uniformize the images/sounds loading
- the other to use gif/wav from $XDG_DATA_HOME/bambam/data

Sorry for these circonvolutions, I'm not yet familiar to pull request mecanism.

Regards

**Comment by porridge** [comment]
You can update the current pull request by doing something like:

git rebase -i porridge/master  # (or whatever name my master branch you can
see at)
git push origin +master  # this will rewrite history, but it's fine since I
didn't merge it yet

**Comment by porridge** [comment]
What's the status of this PR? Are there any changes left here that you'd like to merge?

**Comment by mgodlewski** [comment]
Hi,

Yes, I 've got some changes to introduce :
- use gif/wav from $XDG_DATA_HOME/bambam/data

But this PR is too messy. I'll made another one. You can close this one.

Regards,

Mathieu

**Pull request closed without merging**
